; STM32F103C8T6 — 多传感器采集监测系统
[env:bluepill_f103c8]
platform = ststm32@19.5.0
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
build_type = release
build_flags =
  -Iinclude
  -Wall
  -Wextra
  -Wno-unused-parameter
  -Os
  -ffunction-sections
  -fdata-sections
  -u_printf_float
build_src_filter = +<*> -<.git/> -<svn/>
monitor_speed = 115200
